# Guestbook frontend deployment (v2)
# Updated version of the application used to demonstrate
# rolling updates and rollback behavior in Kubernetes.
# This deployment replaces v1 using the same Deployment name.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
  labels:
    app: analyzer
spec:
  selector:
    matchLabels:
      app: analyzer
  replicas: 1
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: analyzer
        image: us.icr.io/<my_namespace>/analyzer:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: TONE_ANALYZER_API_KEY
          valueFrom:
            secretKeyRef:
              name: binding-tone
              key: apikey
        - name: TONE_ANALYZER_SERVICE_API
          valueFrom:
            secretKeyRef:
              name: binding-tone
              key: url
        ports:
        - containerPort: 5000
          name: http
